# Generated by Django 4.2.7 on 2023-11-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0002_inicializar_padroes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default='0', max_length=11),
            preserve_default=False,
        ),
    ]
