# Generated by Django 4.2.7 on 2023-11-17 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0004_alter_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='id_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshop.usuario'),
        ),
    ]
