# Generated by Django 4.2.7 on 2024-06-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0005_alter_agendamento_id_pet_alter_pet_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='receber_notificacoes',
            field=models.BooleanField(default=True),
        ),
    ]
